import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Esperanza Club",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="w-full h-16 bg-background2  shadow-2xl shadow-background3 text-white">
                    <img src="./assets/esperanza_logo (no bg).png" alt="esperanzalogo" width={70} className="ml-10 md:ml-28"/></div>
                {children}
            </body>
        </html>
    )
}
