import type { Metadata } from "next"
import { Toaster } from "@/components/ui/sonner"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Esperanza Club",
    description: "Generated by create next app",
    icons: ["/assets/icon_logo.svg"],
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="dark">
            <body className={`${inter.className} bg-slate-900`}>
                <Toaster />
                {children}
            </body>
        </html>
    )
}
