import type { Metadata } from "next"
import NavigationBar from "@/components/shared/NavigationBar"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Esperanza Club",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NavigationBar />
                {children}
            </body>
        </html>
    )
}
